# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d81a75ed95ca295a0c4747a3e3833e19af7ca634ea918b53b6f45f2ce882b813cea50f247e701fee1347d722255cc676fe89e5ab3e2faab190ff69eeb96a2887

test:
  secret_key_base: 65adb3ebe9b20a1920369dccc44d9935763016b3d717d78237c1586d3f8adf97d233a0e16a0ae993264049601090fae5eee8714a8cdbe01530ae84fc22f58f84

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
